network:
  name: grod_net
  num_classes: '@{dataset.num_classes}'
  pretrained: False # In training pipeline:"False"; In testing pipeline:"True"
  num_gpus: '@{num_gpus}'
  checkpoint: none
  feat_dim: 1

  backbone:
    name: vit-b-16
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: True
    checkpoint: "/home/yahao/ZYJ/OpenOOD/results/vit_b_16-c867db91.pth"
    num_gpus: '@{num_gpus}'
