seed: 42
seed_data: 42
device: 'cuda:0'
### Roots
train_root: " "
test_root: " "
output_path: " "
postfix: ' ' 
### Model & Schemes m = (d, h, mh, mV , r)
batch_size:
m_V:
m_h:
d:
r:
h:
d0:
n:
N:
K:
mode_c:
mode_E:
lambda0:
T:
l:
### Loss Superpara
gamma:
### Training Configurations
num_workers: 15
batch_size: 64
learning_rate: 5.0e-4
weight_decay: 1.0e-5
min_learning_rate: 5.0e-6
T_max: 10
epochs: 100
patience: 8